// Read-only fallback captured from Printables' public GraphQL taxonomy on
// 2026-07-28. The Worker normally serves live data and refreshes its edge
// cache daily; this snapshot keeps the upload form usable during upstream
// throttling or a transient Printables outage.

type CategoryRow = [id: string, name: string, level: number, parent?: string];

const CATEGORY_ROWS: CategoryRow[] = [
  ["1", "3D Printers", 0],
  ["134", "Prusa Parts & Upgrades", 1, "3D Printers"],
  ["40", "Accessories", 1, "3D Printers"],
  ["138", "Anycubic Parts & Upgrades", 1, "3D Printers"],
  ["136", "Bambu Lab Parts & Upgrades", 1, "3D Printers"],
  ["135", "Creality Parts & Upgrades", 1, "3D Printers"],
  ["2", "Other Printer Parts & Upgrades", 1, "3D Printers"],
  ["137", "Voron Parts & Upgrades", 1, "3D Printers"],
  ["12", "Test Models", 1, "3D Printers"],
  ["13", "Art & Design", 0],
  ["16", "2D Plates & Logos", 1, "Art & Design"],
  ["14", "Sculptures", 1, "Art & Design"],
  ["15", "Wall-mounted", 1, "Art & Design"],
  ["41", "Other Art & Designs", 1, "Art & Design"],
  ["76", "Costumes & Accessories", 0],
  ["77", "Cosplay & Costumes in general", 1, "Costumes & Accessories"],
  ["78", "Masks", 1, "Costumes & Accessories"],
  ["81", "Props", 1, "Costumes & Accessories"],
  ["80", "Other Costume Accessories", 1, "Costumes & Accessories"],
  ["17", "Fashion", 0],
  ["18", "Men", 1, "Fashion"],
  ["20", "Women", 1, "Fashion"],
  ["42", "Other Fashion Accessories", 1, "Fashion"],
  ["21", "Gadgets", 0],
  ["25", "Audio", 1, "Gadgets"],
  ["27", "Computers", 1, "Gadgets"],
  ["26", "Photo & Video", 1, "Gadgets"],
  ["28", "Portable Devices", 1, "Gadgets"],
  ["100", "Video Games", 1, "Gadgets"],
  ["140", "Virtual Reality", 1, "Gadgets"],
  ["43", "Other Gadgets", 1, "Gadgets"],
  ["87", "Healthcare", 0],
  ["88", "Home Medical Tools", 1, "Healthcare"],
  ["99", "Medical Tools", 1, "Healthcare"],
  ["48", "Hobby & Makers", 0],
  ["89", "Automotive", 1, "Hobby & Makers"],
  ["52", "Electronics", 1, "Hobby & Makers"],
  ["51", "Mechanical Parts", 1, "Hobby & Makers"],
  ["95", "Music", 1, "Hobby & Makers"],
  ["50", "Organizers", 1, "Hobby & Makers"],
  ["64", "RC & Robotics", 1, "Hobby & Makers"],
  ["49", "Tools", 1, "Hobby & Makers"],
  ["82", "Other Ideas", 1, "Hobby & Makers"],
  ["3", "Household", 0],
  ["5", "Bathroom", 1, "Household"],
  ["6", "Bedroom", 1, "Household"],
  ["139", "Garage", 1, "Household"],
  ["44", "Home Decor", 1, "Household"],
  ["4", "Kitchen", 1, "Household"],
  ["7", "Living Room", 1, "Household"],
  ["29", "Office", 1, "Household"],
  ["53", "Outdoor & Garden", 1, "Household"],
  ["45", "Other House Equipment", 1, "Household"],
  ["57", "Pets", 1, "Household"],
  ["90", "Learning", 0],
  ["92", "Chemistry & Biology", 1, "Learning"],
  ["93", "Engineering", 1, "Learning"],
  ["98", "Haptic Models", 1, "Learning"],
  ["94", "Math", 1, "Learning"],
  ["96", "Other 3D Objects for Learning", 1, "Learning"],
  ["91", "Physics & Astronomy", 1, "Learning"],
  ["65", "Seasonal designs", 0],
  ["69", "Autumn & Halloween", 1, "Seasonal designs"],
  ["68", "Spring & Easter", 1, "Seasonal designs"],
  ["71", "Summer", 1, "Seasonal designs"],
  ["70", "Winter & Christmas & New Year's", 1, "Seasonal designs"],
  ["9", "Sports & Outdoor", 0],
  ["84", "Indoor Sports", 1, "Sports & Outdoor"],
  ["85", "Other Sports", 1, "Sports & Outdoor"],
  ["83", "Outdoor Sports", 1, "Sports & Outdoor"],
  ["74", "Winter Sports", 1, "Sports & Outdoor"],
  ["101", "Tabletop Miniatures", 0],
  ["97", "Characters & Monsters", 1, "Tabletop Miniatures"],
  ["104", "Miniature Gaming Accessories", 1, "Tabletop Miniatures"],
  ["103", "Props & Terrains", 1, "Tabletop Miniatures"],
  ["105", "Vehicles & Machines", 1, "Tabletop Miniatures"],
  ["30", "Toys & Games", 0],
  ["36", "Action Figures & Statues", 1, "Toys & Games"],
  ["31", "Board Games", 1, "Toys & Games"],
  ["37", "Building Toys", 1, "Toys & Games"],
  ["34", "Outdoor Toys", 1, "Toys & Games"],
  ["33", "Puzzles & Brain-teasers", 1, "Toys & Games"],
  ["38", "Vehicles", 1, "Toys & Games"],
  ["47", "Other Toys & Games", 1, "Toys & Games"],
  ["58", "World & Scans", 0],
  ["61", "Animals", 1, "World & Scans"],
  ["62", "Architecture & Urbanism", 1, "World & Scans"],
  ["75", "Historical Context", 1, "World & Scans"],
  ["60", "People", 1, "World & Scans"],
];

export const PRINTABLES_META_SNAPSHOT = {
  categories: CATEGORY_ROWS.map(([id, name, level, parent]) => ({
    id,
    name,
    nameEn: name,
    level,
    path: parent
      ? [{ id: '', name: parent, nameEn: parent }, { id, name, nameEn: name }]
      : [{ id, name, nameEn: name }],
  })),
  licenses: [
    { id: "7", name: "Creative Commons — Public Domain", disallowRemixing: false, freeModels: true, storeModels: false, isSelectable: true },
    { id: "1", name: "Creative Commons — Attribution", disallowRemixing: false, freeModels: true, storeModels: false, isSelectable: true },
    { id: "2", name: "Creative Commons — Attribution  — Share Alike", disallowRemixing: false, freeModels: true, storeModels: false, isSelectable: true },
    { id: "8", name: "Creative Commons — Attribution — NoDerivatives", disallowRemixing: true, freeModels: true, storeModels: false, isSelectable: true },
    { id: "3", name: "Creative Commons — Attribution  — Noncommercial", disallowRemixing: false, freeModels: true, storeModels: false, isSelectable: true },
    { id: "4", name: "Creative Commons — Attribution  — Noncommercial  —  Share Alike", disallowRemixing: false, freeModels: true, storeModels: false, isSelectable: true },
    { id: "6", name: "Creative Commons — Attribution  — Noncommercial  —  NoDerivatives", disallowRemixing: true, freeModels: true, storeModels: false, isSelectable: true },
    { id: "9", name: "GNU General Public License v2.0", disallowRemixing: false, freeModels: true, storeModels: false, isSelectable: true },
    { id: "12", name: "GNU General Public License v3.0", disallowRemixing: false, freeModels: true, storeModels: false, isSelectable: true },
    { id: "10", name: "GNU Lesser General Public License", disallowRemixing: false, freeModels: true, storeModels: false, isSelectable: true },
    { id: "11", name: "BSD License", disallowRemixing: false, freeModels: true, storeModels: false, isSelectable: true },
    { id: "13", name: "Standard Digital File License", disallowRemixing: true, freeModels: true, storeModels: true, isSelectable: true },
    { id: "14", name: "Commercial Use - No Derivative", disallowRemixing: true, freeModels: false, storeModels: true, isSelectable: true },
    { id: "15", name: "Commercial Use", disallowRemixing: true, freeModels: false, storeModels: true, isSelectable: true },
    { id: "16", name: "Open Community License v1", disallowRemixing: false, freeModels: true, storeModels: false, isSelectable: false },
    { id: "17", name: "Open Community License v1.1", disallowRemixing: false, freeModels: true, storeModels: false, isSelectable: true },
    { id: "19", name: "Open Community License v1.1 + General Attribution v1", disallowRemixing: false, freeModels: true, storeModels: false, isSelectable: true },
    { id: "20", name: "Open Community License v1.1 + Research & Development v1", disallowRemixing: false, freeModels: true, storeModels: false, isSelectable: true },
    { id: "21", name: "Open Community License v1.1 + Micro Business v1", disallowRemixing: false, freeModels: true, storeModels: false, isSelectable: true },
    { id: "22", name: "Open Community License v1.1 + GAtt v1 + Micro v1", disallowRemixing: false, freeModels: true, storeModels: false, isSelectable: true },
    { id: "23", name: "Open Community License v1.1 + GAtt v1 + RnD v1", disallowRemixing: false, freeModels: true, storeModels: false, isSelectable: true },
    { id: "18", name: "CERN Open Hardware Licence Version 2 - Strongly Reciprocal", disallowRemixing: false, freeModels: true, storeModels: false, isSelectable: true },
  ],
};
