import { describe, expect, it } from 'vitest';
import JSZip from 'jszip';
import { detectSlicerFromApplication, fileSlicer, parseThreeMF, slicerLabel } from './threemf.js';

const loadZip = async () => JSZip;

async function makeZip(entries) {
  const zip = new JSZip();
  for (const [name, content] of Object.entries(entries)) zip.file(name, content);
  return zip.generateAsync({ type: 'uint8array' });
}

const bambuModel = '<?xml version="1.0"?><model><metadata name="Application">BambuStudio-01.09.00.60</metadata></model>';
const bambuSliceInfo = `<?xml version="1.0"?><config>
  <plate><metadata key="index" value="1"/><metadata key="prediction" value="5400"/><metadata key="weight" value="42.7"/></plate>
  <header_item key="X-BBL-Client-Type" value="slicer"/>
</config>`;
const bambuProjectSettings = JSON.stringify({
  printer_model: 'Bambu Lab A1 mini',
  filament_type: ['PLA'],
  layer_height: '0.2',
  sparse_infill_density: '15%',
});

describe('3mf slicer detection', () => {
  it('identifies a Bambu Studio package with its print settings', async () => {
    const blob = await makeZip({
      '3D/3dmodel.model': bambuModel,
      'Metadata/slice_info.config': bambuSliceInfo,
      'Metadata/project_settings.config': bambuProjectSettings,
    });
    const parsed = await parseThreeMF(blob, loadZip);
    expect(parsed.slicer).toBe('bambu');
    expect(parsed.sliced).toBe(true);
    expect(parsed.printer).toBe('Bambu Lab A1 mini');
    expect(parsed.material).toBe('PLA');
    expect(parsed.layerHeight).toBe('0.2mm');
    expect(parsed.plates).toBe(1);
  });

  it('identifies Orca-family derivatives by their Application string', async () => {
    for (const [app, expected] of [
      ['ElegooSlicer-1.0.2', 'elegoo'],
      ['Creality Print 5.1', 'crealityprint'],
      ['OrcaSlicer-2.1.1', 'orca'],
      ['AnycubicSlicerNext 1.3', 'anycubic'],
    ]) {
      const blob = await makeZip({
        '3D/3dmodel.model': `<model><metadata name="Application">${app}</metadata></model>`,
      });
      const parsed = await parseThreeMF(blob, loadZip);
      expect(parsed.slicer).toBe(expected);
    }
  });

  it('identifies PrusaSlicer by its Slic3r_PE.config fingerprint', async () => {
    const blob = await makeZip({
      '3D/3dmodel.model': '<model></model>',
      'Metadata/Slic3r_PE.config': '; generated by PrusaSlicer\nprinter_model = MK4\nfilament_type = PETG\nlayer_height = 0.15\n',
    });
    const parsed = await parseThreeMF(blob, loadZip);
    expect(parsed.slicer).toBe('prusa');
    expect(parsed.sliced).toBe(true);
    expect(parsed.printer).toBe('MK4');
    expect(parsed.material).toBe('PETG');
  });

  it('reclassifies a Bambu-branded fork by its target printer (real Anycubic case)', async () => {
    // Anycubic Slicer Next keeps upstream's "BambuStudio-1.4.1.0" Application
    // string; the printer_model is the reliable signal.
    const blob = await makeZip({
      '3D/3dmodel.model': '<model><metadata name="Application">BambuStudio-1.4.1.0</metadata></model>',
      'Metadata/slice_info.config': '<config><header><header_item key="X-BBL-Client-Type" value="slicer"/></header></config>',
      'Metadata/project_settings.config': JSON.stringify({ printer_model: 'Anycubic Kobra 3 Max', filament_type: ['PLA'], layer_height: '0.16' }),
    });
    const parsed = await parseThreeMF(blob, loadZip);
    expect(parsed.slicer).toBe('anycubic');
    expect(parsed.printer).toBe('Anycubic Kobra 3 Max');
  });

  it('keeps genuine Bambu Studio files classified as bambu', async () => {
    const blob = await makeZip({
      '3D/3dmodel.model': '<model><metadata name="Application">BambuStudio-02.07.01.62</metadata></model>',
      'Metadata/slice_info.config': '<config><header><header_item key="X-BBL-Client-Type" value="slicer"/></header></config>',
      'Metadata/project_settings.config': JSON.stringify({ printer_model: 'Bambu Lab X1 Carbon', filament_type: ['PLA'], layer_height: '0.16' }),
    });
    const parsed = await parseThreeMF(blob, loadZip);
    expect(parsed.slicer).toBe('bambu');
  });

  it('marks a plain CAD-exported 3mf as unknown and unsliced', async () => {
    const blob = await makeZip({ '3D/3dmodel.model': '<model><metadata name="Application">SolidWorks</metadata></model>' });
    const parsed = await parseThreeMF(blob, loadZip);
    expect(parsed.slicer).toBe('unknown');
    expect(parsed.sliced).toBe(false);
  });

  it('never throws on a file that is not a ZIP at all', async () => {
    const parsed = await parseThreeMF(new Blob(['solid cube not a zip']), loadZip);
    expect(parsed).toMatchObject({ slicer: 'unknown', sliced: false, scanned: true });
  });

  it('lets a user override win over the detected slicer', () => {
    expect(fileSlicer({ threemf: { slicer: 'orca' }, slicerOverride: 'bambu' })).toBe('bambu');
    expect(fileSlicer({ threemf: { slicer: 'orca' } })).toBe('orca');
    expect(fileSlicer({})).toBe('unknown');
    expect(slicerLabel('elegoo')).toBe('Elegoo Slicer');
  });

  it('maps application strings without needing a package', () => {
    expect(detectSlicerFromApplication('BambuStudio-02.00')).toBe('bambu');
    expect(detectSlicerFromApplication('')).toBe('unknown');
  });
});
